apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bot-scaler-account
  namespace: develop
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bot-scaler-account-binding
  namespace: develop
roleRef:
  apiGroup: rbac.authorization.k8s.io
  name: bot-scaler-account
  kind: Role
subjects:
- kind: ServiceAccount
  name: bot-scaler-account
